//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yonetmenler()
        {
            this.Filmlers = new HashSet<Filmler>();
        }
    
        public int YonetmenID { get; set; }
        public string YonetmenAdi { get; set; }
        public string YonetmenSoyadi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filmler> Filmlers { get; set; }
    }
}
